default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: sampleadmin
  password: sampleadminp
  socket: /var/lib/mysql/mysql.sock

default2: &default2
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: sampleadmin
  password: sampleadminp
  socket: /var/lib/mysql/mysql.sock

development:
  <<: *default
  database: sampleadmin_development

development2:
  <<: *default2
  database: sampleadmin_development

test:
  <<: *default
  database: sampleadmin_test

test2:
  <<: *default2
  database: sampleadmin_test
# As with config/secrets.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is
# ever seen by anyone, they now have access to your database.
#
# Instead, provide the password as a unix environment variable when you boot
# the app. Read http://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full rundown on how to provide these environment variables in a
# production deployment.
#
# On Heroku and other platform providers, you may have a full connection URL
# available as an environment variable. For example:
#
#   DATABASE_URL="mysql2://myuser:mypass@localhost/somedatabase"
#
# You can use this database configuration with:
#
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
production:
  <<: *default
  database: sampleadmin
  username: sampleadmin
  password: <%= ENV['SAMPLE-ADMIN_DATABASE_PASSWORD'] %>

production2:
  <<: *default2
  database: sampleadmin
  username: sampleadmin
  password: <%= ENV['SAMPLE-ADMIN_DATABASE_PASSWORD'] %>
